apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram
    group_by: ['device']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h     # re-notify every 12 h while still firing
